# Generated by Django 5.1.7 on 2025-04-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencybloodrequest',
            name='contact',
            field=models.CharField(default=0, help_text='Contact number for further communication.', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencybloodrequest',
            name='hospital_name',
            field=models.CharField(default=0, help_text='Name of the hospital.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencybloodrequest',
            name='location',
            field=models.CharField(default=0, help_text='Location where blood is needed.', max_length=255),
            preserve_default=False,
        ),
    ]
